#!/bin/sh

set -e
echo "=> Installing PWM-curve script\n"

sudo cp fan-pwm.py /usr/local/bin/
sudo chmod +x /usr/local/bin/fan-pwm.py
sudo cp fan-pwm.service /etc/systemd/system/
sudo systemctl enable fan-pwm.service
sudo systemctl start fan-pwm.service

echo "Fan PWM script installed.\n"
